# <span style="color:darkblue"> QTM 151 - Quiz 3 </span>

## Try to submit as an HTML file

<font size="5"> 

Print your name below

In [3]:
# Write your answer here

print("Turner Goetsch")

Turner Goetsch

<font size = "5" >
This quiz is open book 

- You can use the lecture notes
- You will get partial credit for attempting the questions
- To get full credit, the code should run as intended
- You should <span style="color:red"> NOT </span> communicate with other students

Print the following message: <br>

"I will abide by Emory's code of conduct"

In [4]:
# Write your answer here:

print("I will abide by Emory's code of conduct")

I will abide by Emory's code of conduct

<font size = "5">

Import the libraries "numpy" and "pandas"

In [5]:
# Write your answer here

import numpy as np
import pandas as pd


<font size = "5">

(a) Replace the values of a column

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Replace the values "R" and "N" with ```np.nan``` (missing value) <br>
in the column "positionText"
- Create a new column "positionNumeric" that converts <br>
the modified "positionText" column from string to numeric <br>
using ```pd.to_numeric()```

HINT: See the example in Lecture 13

In [6]:
# Write your own code

sprint_results = pd.read_csv("data_raw/sprint_results.csv")


list_old = ["R", "N"]
list_new = [np.nan]

sprint_results["positionText"] = sprint_results["positionText"].replace("R", np.nan)
sprint_results["positionText"] = sprint_results["positionText"].replace("N", np.nan)

sprint_results["positionNumeric"] = pd.to_numeric(sprint_results["positionText"])

<font size = "5">

(b) Recode a numeric colum

<font size = "3">

- Import the "data_raw/races.csv" file
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories

$\qquad$ ``` ["1950-1974","1975-1999","2000-onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [7]:
# Write your own code

races = pd.read_csv("data_raw/races.csv")

bins_labels = ["1950-1974", "1975-1999", "2000-onwards"]
bins_years = [1949, 1974, 1999, 2100]

races["year_brackets"] = pd.cut(races["year"],
                                bins = bins_years,
                                right = True,
                                labels = bins_labels)

races["year_brackets"]

0       2000-onwards
1       2000-onwards
2       2000-onwards
3       2000-onwards
4       2000-onwards
            ...
1097    2000-onwards
1098    2000-onwards
1099    2000-onwards
1100    2000-onwards
1101    2000-onwards
Name: year_brackets, Length: 1102, dtype: category
Categories (3, object): ['1950-1974' < '1975-1999' < '2000-onwards']

<font size = "5">

(c) Aggregate and query

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Subset the observations for 'constructorId == 3' using ```.query()```
- Obtain the sum of "laps" by "driverId" <br> 
 using ``` .groupby().agg() ```
- Subset the drivers with a sum of laps $\ge 40$
- Store the results of all these operations in a dataframe <br>
```sprint_results_agg ```

In [12]:
# Write your own code
sprint_results1 = pd.read_csv("data_raw/sprint_results.csv")

sprint_results_sums = (sprint_results1.query('constructorId == 3')
                      .groupby("driverId")
                      .agg(laps_sum = ('laps', 'sum')))

sprint_results_agg = sprint_results_sums.query('laps_sum >= 40')

sprint_results_agg

          laps_sum
driverId
847             59
848             56
849            127

<font size = "5">

(d) Aggregate and sort

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Obtain the sum of "laps" by "driverId" <br> 
using ``` .groupby().agg() ```
- Sort the teams in descending order using of <br>
the sum of laps using ``` .sort_values() ```

In [9]:
# Write your own code
sprint_results2 = pd.read_csv("data_raw/sprint_results.csv")

sprint_results_agg2 = (sprint_results2.groupby("driverId")
                  .agg(laps_sum = ("laps", 'sum'))
                  .sort_values('laps_sum', ascending= False))

<font size = "5">

(e) Rename column

<font size = "3">

- Import the "data_raw/sprint_results.csv" file
- Rename the column "points" to "points_sprint"

HINT: Create a dictionary and use ```.rename(columns = ...)``` <br>
See Lecture 15

In [10]:
# Write your own code

sprint_results3 = pd.read_csv("data_raw/sprint_results.csv")

dict_rename_column = {"points": "points_sprint"}

sprint_new_results = sprint_results3.rename(columns = dict_rename_column)

<font size = "5">

(f) Merge dataset

<font size = "3">

- Import the "data_raw/sprint_results.csv" and <br>
"data_raw/constructors.csv" files
- Create a new dataset with  ```pd.merge()``` using <br>
"sprint_results" as the primary dataset, and <br>
"constructors" as the secondary dataset, merging on <br>
the column "constructorId"
- To get full points **ONLY** merge the "url" column <br>
from the secondary dataset (not all the columns)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging, including the <br>
"constructorId" column

In [11]:
# Write your own code

sprint_results4 = pd.read_csv("data_raw/sprint_results.csv")

constructors_data = pd.read_csv("data_raw/constructors.csv")

data_merged = pd.merge(sprint_results4,
                       constructors_data[["constructorId","url"]],
                       on= "constructorId",
                       how= "left")

sprint_results4
data_merged

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,fastestLapTime,statusId,url
0,1,1061,830,9,33,2,1,1,1,3,17,25:38.426,1538426,14,1:30.013,1,http://en.wikipedia.org/wiki/Red_Bull_Racing
1,2,1061,1,131,44,1,2,2,2,2,17,+1.430,1539856,17,1:29.937,1,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...
2,3,1061,822,131,77,3,3,3,3,1,17,+7.502,1545928,17,1:29.958,1,http://en.wikipedia.org/wiki/Mercedes-Benz_in_...
3,4,1061,844,6,16,4,4,4,4,0,17,+11.278,1549704,16,1:30.163,1,http://en.wikipedia.org/wiki/Scuderia_Ferrari
4,5,1061,846,1,4,6,5,5,5,0,17,+24.111,1562537,16,1:30.566,1,http://en.wikipedia.org/wiki/McLaren
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,116,1095,840,117,18,15,16,16,16,0,24,+50.700,1862007,4,1:15.425,1,http://en.wikipedia.org/wiki/Aston_Martin_in_F...
116,117,1095,839,214,31,6,17,17,17,0,24,+51.756,1863063,5,1:16.097,1,http://en.wikipedia.org/wiki/Alpine_F1_Team
117,118,1095,4,214,14,7,18,18,18,0,24,+53.985,1865292,5,1:14.764,1,http://en.wikipedia.org/wiki/Alpine_F1_Team
118,119,1095,849,3,6,16,19,19,19,0,24,+1:16.850,1888157,4,1:16.525,1,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
119,120,1095,848,3,23,11,\N,R,20,0,12,\N,\N,4,1:15.998,31,http://en.wikipedia.org/wiki/Williams_Grand_Pr...